// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaleWebMvc.Models;

namespace SaleWebMvc.Migrations
{
    [DbContext(typeof(SaleWebMvcContext))]
    [Migration("20181022222425_DepartamentoId")]
    partial class DepartamentoId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SaleWebMvc.Models.Department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasMaxLength(20);

                    b.HasKey("id");

                    b.ToTable("DEPARTAMENTOS");
                });

            modelBuilder.Entity("SaleWebMvc.Models.SalesRecord", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("amount")
                        .HasColumnName("total");

                    b.Property<DateTime>("date")
                        .HasColumnName("data_venda");

                    b.Property<int?>("sellerid");

                    b.Property<int>("status");

                    b.HasKey("id");

                    b.HasIndex("sellerid");

                    b.ToTable("VENDAS");
                });

            modelBuilder.Entity("SaleWebMvc.Models.Seller", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId");

                    b.Property<double>("baseSalary")
                        .HasColumnName("salario_base");

                    b.Property<DateTime>("birthDate")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("email")
                        .HasMaxLength(30);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnName("nome_vendedor")
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("VENDEDORES");
                });

            modelBuilder.Entity("SaleWebMvc.Models.SalesRecord", b =>
                {
                    b.HasOne("SaleWebMvc.Models.Seller", "seller")
                        .WithMany()
                        .HasForeignKey("sellerid");
                });

            modelBuilder.Entity("SaleWebMvc.Models.Seller", b =>
                {
                    b.HasOne("SaleWebMvc.Models.Department", "department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
